export const cacheTaskUpdateActiveSql = `
UPDATE cacheTask
SET [active] = @active,
  [activeCheckAt] = @activeCheckAt;`;

export const cacheTaskInsertSql = `
INSERT INTO cacheTask (
  [id],
  [assignerId],
  [assigneeId],
  [projectId],
  [sectionId],
  [parentId],
  [order],
  [content],
  [description],
  [isCompleted],
  [labels],
  [priority],
  [commentCount],
  [creatorId],
  [createdAt],
  [dueDate],
  [dueString],
  [dueLang],
  [dueIsRecurring],
  [dueDatetime],
  [dueTimezone],
  [url],
  [active],
  [activeCheckAt]
)
SELECT @id,
  @assignerId,
  @assigneeId,
  @projectId,
  @sectionId,
  @parentId,
  @order,
  @content,
  @description,
  @isCompleted,
  @labels,
  @priority,
  @commentCount,
  @creatorId,
  @createdAt,
  @dueDate,
  @dueString,
  @dueLang,
  @dueIsRecurring,
  @dueDatetime,
  @dueTimezone,
  @url,
  @active,
  @activeCheckAt;`;

export const cacheTaskUpdateSql = `
UPDATE cacheTask
SET [assignerId] = @assignerId,
  [assigneeId] = @assigneeId,
  [projectId] = @projectId,
  [sectionId] = @sectionId,
  [parentId] = @parentId,
  [order] = @order,
  [content] = @content,
  [description] = @description,
  [isCompleted] = @isCompleted,
  [labels] = @labels,
  [priority] = @priority,
  [commentCount] = @commentCount,
  [creatorId] = @creatorId,
  [createdAt] = @createdAt,
  [dueDate] = @dueDate,
  [dueString] = @dueString,
  [dueLang] = @dueLang,
  [dueIsRecurring] = @dueIsRecurring,
  [dueDatetime] = @dueDatetime,
  [dueTimezone] = @dueTimezone,
  [url] = @url,
  [active] = @active,
  [activeCheckAt] = @activeCheckAt
WHERE [id] = @id;`;
